# Generated by Django 4.0.6 on 2022-07-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('photo_1', models.TextField(verbose_name='фото 1')),
                ('photo_2', models.TextField(blank=True, verbose_name='фото 2')),
                ('photo_3', models.TextField(blank=True, verbose_name='фото 3')),
                ('photo_4', models.TextField(blank=True, verbose_name='фото 4')),
                ('photo_5', models.TextField(blank=True, verbose_name='фото 5')),
                ('photo_6', models.TextField(blank=True, verbose_name='фото 6')),
                ('photo_7', models.TextField(blank=True, verbose_name='фото 7')),
                ('photo_8', models.TextField(blank=True, verbose_name='фото 8')),
                ('about', models.TextField(verbose_name='О товаре')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='Цена')),
                ('tema', models.CharField(choices=[('Всё для дома', 'Всё для дома'), ('Компьютерные аксессуары', 'Компьютерные аксессуары'), ('Коврики для мыши', 'Коврики для мыши'), ('Всё для кухни', 'Всё для кухни'), ('Красота и здоровье', 'Красота и здоровье'), ('Автотовары', 'Автотовары'), ('Всё для строительства и ремонта', 'Всё для строительства и ремонта'), ('Велотовары', 'Велотовары'), ('Электронные аксессуары', 'Электронные аксессуары'), ('Б/у техника и товары', 'Б/у техника и товары'), ('Остальное', 'Остальное')], default='Остальное', max_length=32, verbose_name='Тема')),
                ('tegs', models.TextField(verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
