# Generated by Django 4.0.6 on 2022-07-27 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovars',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='tema',
            field=models.CharField(choices=[('На Главную страницу', 'На Главную страницу'), ('Всё для дома', 'Всё для дома'), ('Компьютерные аксессуары', 'Компьютерные аксессуары'), ('Коврики для мыши', 'Коврики для мыши'), ('Всё для кухни', 'Всё для кухни'), ('Красота и здоровье', 'Красота и здоровье'), ('Автотовары', 'Автотовары'), ('Всё для строительства и ремонта', 'Всё для строительства и ремонта'), ('Велотовары', 'Велотовары'), ('Электронные аксессуары', 'Электронные аксессуары'), ('Б/у техника и товары', 'Б/у техника и товары'), ('Остальное', 'Остальное')], default='Остальное', max_length=32, verbose_name='Тема'),
        ),
    ]
