# Generated by Django 4.0.6 on 2022-07-28 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tovars_data_alter_tovars_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_on_of', models.CharField(choices=[('Включить цены', 'Включить цены'), ('Выключить цены', 'Выключить цены')], default='Включить цены', max_length=14, verbose_name='Включить/Выключить цены')),
            ],
        ),
        migrations.AlterField(
            model_name='tovars',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Дата'),
        ),
    ]
