# Generated by Django 4.0.6 on 2022-07-30 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_set_price_alter_tovars_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set_price',
            options={'verbose_name': 'Включить/Выключить цену', 'verbose_name_plural': 'Включить/Выключить цены'},
        ),
        migrations.AlterField(
            model_name='tovars',
            name='data',
            field=models.DateField(default=datetime.date(2022, 7, 30), verbose_name='Дата'),
        ),
    ]
